version: "2"
services:
  app:
    build: ./app
    #image: docker-cours-flask-mysql_app
    #image: backend_ap1:latest
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db
    networks:
      - my_net

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./mysqldata:/var/lib/mysql
    networks:
      - my_net

networks:
      my_net: